# Generated by Django 3.0 on 2024-03-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户名')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='年龄')),
                ('work', models.CharField(blank=True, max_length=200, null=True, verbose_name='职业')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('feel', models.CharField(blank=True, max_length=500, null=True, verbose_name='心情图片')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱地址')),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserHobbyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(blank=True, max_length=200, null=True, verbose_name='感觉好的活动')),
                ('mindfulness', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否冥想打坐')),
                ('mindfulnessTime', models.IntegerField(blank=True, default=0, null=True, verbose_name='冥想打坐频率')),
                ('mindfulnessTopic', models.IntegerField(blank=True, default=0, null=True, verbose_name='冥想打坐主题')),
                ('dedicateTime', models.IntegerField(blank=True, default=0, null=True, verbose_name='今天能练习的时长')),
                ('extInfo', models.CharField(blank=True, max_length=500, null=True, verbose_name='其他补充信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserModel', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '用户爱好信息',
                'verbose_name_plural': '用户爱好信息',
                'db_table': 'UserHobby',
            },
        ),
    ]
