# Generated by Django 3.0 on 2024-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='pwd',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='密码'),
        ),
    ]
