# Generated by Django 5.0.3 on 2024-03-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_remove_usermodel_age_remove_usermodel_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userhobbymodel",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profile",
            },
        ),
        migrations.AlterModelOptions(
            name="usermodel",
            options={
                "verbose_name": "Authentication",
                "verbose_name_plural": "Authentication",
            },
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="activities",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Activities"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="age",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Age"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="dedicateTime",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Availability"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="extInfo",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="feel",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Emoji"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="mindfulness",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Practice Mindfulness?",
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="mindfulnessTime",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Frequency"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="mindfulnessTopic",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Topics/Themes"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="User.usermodel",
                verbose_name="User Information",
            ),
        ),
        migrations.AlterField(
            model_name="userhobbymodel",
            name="work",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Occupation"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="pwd",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Password"
            ),
        ),
        migrations.CreateModel(
            name="UserHealthModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "walkingSpeed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Walking Speed"
                    ),
                ),
                (
                    "bvp",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Blood Volume Pulse"
                    ),
                ),
                (
                    "ecg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Electrocardiography"
                    ),
                ),
                (
                    "eda",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Electrodermal Activity"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperature"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.usermodel",
                        verbose_name="User Information",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Health",
                "verbose_name_plural": "User Health",
                "db_table": "UserHealth",
            },
        ),
    ]
