# Generated by Django 5.0.3 on 2024-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_alter_userhobbymodel_options_alter_usermodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
    ]
