# Generated by Django 5.0.3 on 2024-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_usermodel_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Login"
            ),
        ),
    ]
