# Generated by Django 5.0.3 on 2024-04-23 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_usermodel_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="is_email_verified",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="last_login",
        ),
    ]
